api:
    resource: '.'
    type: 'api_platform'
    prefix: /

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

index:
    path: /
    defaults: { _controller: 'App\Controller\MainController::index' }

